name: Code for ABQ
markdown: kramdown

people:
  alonso:
    first_name: Alonso
    last_name: Indacochea
    title: Community Organizer
    twitter: Alonso_in
    github: aindaco1
    avatar: /images/alonso.png
  noel:
    first_name: Noel
    last_name: Cothren
    title: Community Organizer
    twitter: noeldevelops
    github: noeldevelops
    avatar: /images/noel.png

officers: [alonso, elaine]
contributors: []

gems:
  - jekyll-sitemap
  - jekyll-feed

plugins:
  - jekyll-redirect-from
