name: Code for ABQ
markdown: kramdown

people:
  alonso:
    first_name: Alonso
    last_name: Indacochea
    title: Community Organizer
    twitter: Alonso_in
    github: aindaco1
    avatar: /images/alonso.png
  elaine:
    first_name: Elaine
    last_name: Thomas
    title: Community Organizer
    twitter: ViceroyThomas
    github: ethomas12
    avatar: /images/elaine.png

officers: [alonso, elaine]
contributors: []

gems:
  - jekyll-sitemap
  - jekyll-feed
